export const docsBoardStructure = [
  {
    name: '_id',
    type: 'string',
    description: 'Unique board identifier generated by MongoDB.',
  },
  {
    name: 'userId',
    type: 'string',
    description: 'The ID of the user who owns this board.',
  },
  {
    name: 'title',
    type: 'string',
    description: 'Title of the board displayed in the dashboard.',
  },
  {
    name: 'text',
    type: 'string',
    description: 'Short description or summary of the board.',
  },
  {
    name: 'members',
    type: 'string[]',
    description: 'List of users who are members of this board.',
  },
  {
    name: 'liked',
    type: 'string[]',
    description: 'Array of user IDs who liked this board.',
  },
  {
    name: 'tasksDone',
    type: 'number',
    description: 'Number of completed tasks within the board.',
  },
  {
    name: 'tasks',
    type: 'number',
    description: 'Total number of tasks currently on the board.',
  },
  {
    name: 'access',
    type: 'string',
    description: 'Access level of the board ("locked" or "public").',
  },
  {
    name: 'status',
    type: 'string',
    description: 'Visibility of the board ("in planning" or "action" or "done" or "archived").',
  },
  {
    name: 'image',
    type: 'string (URL)',
    description: 'Link to the preview image of the board.',
  },
  {
    name: 'createdAt',
    type: 'string',
    description: 'Date and time when the board was created.',
  },

];
